# Selections in genetic algorithms

**Selection** is a stage in a genetic algorithm or more general evolutionary algorithm in which individual genomes are chosen from a population for later breeding, using the crossover operator. Selection mechanisms are also used to choose candidate solutions (individuals) for the next generation. 

<span style="color:#EE9977">The primary objective of the selection operator is to emphasize the good solutions and eliminate the bad solutions in a population while keeping the population size constant, giving more chances to the individuals with higher fitness scores to pass their genes to the next generation. </span> There are different methods of selection, such as roulette wheel, tournament, rank-based, etc. and we will walk through some of them together. As mentioned before, selection process can be described by two steps: (1) parents selection and (2) a replacement strategy that decides if offspring will replace parents, and which parent to replace.


<figure>
    <center> <img src="./pics/Selection/selection.png"  alt='missing' width="400"  ><center/>
<figure/>

## **Contents**

<a href='#chrom-def'>01. Chromosome Definition</a>  
 
<a href='#random-select'>02. Random Selection</a>

<a href='#truncation-select'>03. Truncation Selection</a>

<a href='#tournament-select'>04. Tournament Selection</a>

<a href='#self-adapt-tournament-select'>05. Self-Adaptive Tournament Selection</a>

<a href='#boltzmann-select'>06. Boltzmann Selection</a>

<a href='#proportional-select'>07. Proportional Selection</a>

<a href='#fps-select'>08. Fitness Proportionate Selection (FPS)</a>

<a href='#rwsa-select'>09. Roulette Wheel Selection with Stochastic Acceptance (RWSA)</a>

<a href='#sus-select'>10. Stochastic Universal Sampling Selection (SUS)</a>

<a href='#linear-ranking-select'>11. Linear Ranking Selection</a>

<a href='#exponential-ranking-select'>12. Exponential Ranking Selection</a>

<a href='#replace-strategy'>13. Replacement Strategies</a>


## <a id='chrom-def'>Chromosome Definition</a>

First, we need to implement the class chromosome, a function for sorting the population based on fitness, and a function to calculate the fitness of individuals (chromosomes).

In [46]:
import numpy as np

class Chromosome():
    """
    Description of class `Chromosome`:
    This class represents a simple chromosome. In the method describe, a simple description
    of the chromosome is provided, when it is called. 
    """
    def __init__(self, genes, id_=None, fitness=-1):
        self.id_ = id_
        self.genes = genes
        self.fitness = fitness       
       
    def describe(self): 
        """
        Prints the ID, fitness, and genes
        """
        print(f"ID=#{self.id_}, Fitness={self.fitness}, \nGenes=\n{self.genes}")
 
    def get_chrom_length(self): 
        """
        Returns the length of `self.genes`
        """
        return len(self.genes)


def fitness_function(chrom): 
    """
    This function, takes a chromosome and returns a value as its fitness.
    Fitness is calculated by the number of 1's in a bainary chromosome. 
    chrom: The chromoseme which its fitness is calculated and returned.
    """  
    fitness = 0
    for i in range(len(chrom)):
        if chrom[i]==1:
            fitness += 1
    return fitness


def pop_sort(pop):
    """
    This function sorts the population based on their fitnesses, using selection sort.
    pop: The population that are sorted based on their fitnesses.
    """  
    for i in range(len(pop)): 
        min_index = i 
        for j in range(i+1, len(pop)): 
            if pop[min_index].fitness > pop[j].fitness: 
                min_index = j        
        pop[i], pop[min_index] = pop[min_index], pop[i]    
    return pop



## <a id='random-select'>Random Selection</a>

Random selection is a selection mechanism in evolutionary algorithms that selects individuals from a population randomly with uniform probability, regardless of their fitness. This means that the selection pressure is low, and the algorithm may take longer to converge to a good solution. Random selection is different from genetic algorithms because it starts with a completely blank sheet every time, generating a new random solution each iteration, with no memory of what happened before during the previous iterations. 

In [47]:
def random_selection(selection_size, pop):
    """
    In Random Selection, each individual has the probability of 1/pop_size, 
    to be selected (least selection pressure). 
    selection_size: Number of individuals to be selected within the population.
    pop: The population which we want to select a number of individuals among them
    """  
    pop_size = len(pop) #Size of the population
    assert selection_size <= pop_size, "Selection size can't be greater than the population size."
    select = []

    for _ in range(selection_size):
        select.append(pop[np.random.randint(0,pop_size)])
        
    return select


POP = []
chrom0 = np.array([0,1,1,0,1,0,0,0,0,1,0])
chrom1 = np.array([0,1,0,0,0,0,0,0,1,0,0])
chrom2 = np.array([0,1,0,0,0,0,1,0,0,1,0])
chrom3 = np.array([0,1,0,0,1,0,1,0,0,1,0])
chrom4 = np.array([0,0,1,0,1,0,0,1,0,1,0])
chrom5 = np.array([0,1,0,0,0,1,0,1,0,1,0])
chrom6 = np.array([0,1,0,1,1,1,1,0,1,0,0])
chrom7 = np.array([0,1,0,0,1,1,1,1,1,1,1])
chrom8 = np.array([1,1,1,0,1,1,1,1,1,1,0])
chrom9 = np.array([0,0,0,0,0,0,0,1,0,1,0])

POP.append(Chromosome(chrom0, id_= 0, fitness = fitness_function(chrom0)))
POP.append(Chromosome(chrom1, id_= 1, fitness = fitness_function(chrom1)))
POP.append(Chromosome(chrom2, id_= 2, fitness = fitness_function(chrom2)))
POP.append(Chromosome(chrom3, id_= 3, fitness = fitness_function(chrom3)))
POP.append(Chromosome(chrom4, id_= 4, fitness = fitness_function(chrom4)))
POP.append(Chromosome(chrom5, id_= 5, fitness = fitness_function(chrom5)))
POP.append(Chromosome(chrom6, id_= 6, fitness = fitness_function(chrom6)))
POP.append(Chromosome(chrom7, id_= 7, fitness = fitness_function(chrom7)))
POP.append(Chromosome(chrom8, id_= 8, fitness = fitness_function(chrom8)))
POP.append(Chromosome(chrom9, id_= 9, fitness = fitness_function(chrom9)))

# print("\nThe Population:")
# print("========================================")
# for i in range(len(POP)): #printing the population
#     Chromosome.describe(POP[i])

SELECTION = random_selection(3, POP)

print("\nSelected Individuals:")
print("========================================")
for i in range(len(SELECTION)): #printing the selected individuals
    Chromosome.describe(SELECTION[i])



Selected Individuals:
ID=#8, Fitness=9, 
Genes=
[1 1 1 0 1 1 1 1 1 1 0]
ID=#3, Fitness=4, 
Genes=
[0 1 0 0 1 0 1 0 0 1 0]
ID=#0, Fitness=4, 
Genes=
[0 1 1 0 1 0 0 0 0 1 0]


## <a id='truncation-select'>Truncation Selection</a>

Truncation selection is a selection mechanism in evolutionary algorithms that selects the fittest individuals from a population and retains them for the next generation. Truncation selection has the greatest selection pressure. The fittest individuals are duplicated so that the population size is maintained. Truncation selection is less sophisticated than many other selection methods, and it is not often used in practice. 


In [48]:
def truncation_selection(selection_size, pop):
    """
    In Truncation Selection, Only the fittest members of the population will be selected
    and these individuals will be duplicated to maintain the population.
    This function takes a population, and returns the fittest ones inside.
    selection_size: Number of individuals to be selected within the population.
    pop_size: Size of the population
    pop: The population which we want to select a number of individuals among them. 
    """  
    pop_size = len(pop) # size of the population
    assert selection_size <= pop_size, "Selection size can't be greater than the population size."
    sorted_pop = pop_sort(pop)
    select = []

    #assuring that the selection size is less than the size of the population
    if selection_size > pop_size: 
        selection_size = pop_size

    # selecting the individuals with best fitnesses
    select = sorted_pop[-selection_size:]

    return select


POP = []
chrom0 = np.array([0,1,1,0,1,0,0,0,0,1,0])
chrom1 = np.array([0,1,0,0,0,0,0,0,1,0,0])
chrom2 = np.array([0,1,0,0,0,0,1,0,0,1,0])
chrom3 = np.array([0,1,0,0,1,0,1,0,0,1,0])
chrom4 = np.array([0,0,1,0,1,0,0,1,0,1,0])
chrom5 = np.array([0,1,0,0,0,1,0,1,0,1,0])
chrom6 = np.array([0,1,0,1,1,1,1,0,1,0,0])
chrom7 = np.array([0,1,0,0,1,1,1,1,1,1,1])
chrom8 = np.array([1,1,1,0,1,1,1,1,1,1,0])
chrom9 = np.array([0,0,0,0,0,0,0,1,0,1,0])

POP.append(Chromosome(chrom0, id_= 0, fitness = fitness_function(chrom0)))
POP.append(Chromosome(chrom1, id_= 1, fitness = fitness_function(chrom1)))
POP.append(Chromosome(chrom2, id_= 2, fitness = fitness_function(chrom2)))
POP.append(Chromosome(chrom3, id_= 3, fitness = fitness_function(chrom3)))
POP.append(Chromosome(chrom4, id_= 4, fitness = fitness_function(chrom4)))
POP.append(Chromosome(chrom5, id_= 5, fitness = fitness_function(chrom5)))
POP.append(Chromosome(chrom6, id_= 6, fitness = fitness_function(chrom6)))
POP.append(Chromosome(chrom7, id_= 7, fitness = fitness_function(chrom7)))
POP.append(Chromosome(chrom8, id_= 8, fitness = fitness_function(chrom8)))
POP.append(Chromosome(chrom9, id_= 9, fitness = fitness_function(chrom9)))

# print("\nThe Population:")
# print("========================================")
# for i in range(len(POP)): #printing the population
#     Chromosome.describe(POP[i])


SELECTION = truncation_selection(3, POP)

print("\nSelected Individuals:")
print("========================================")
for i in range(len(SELECTION)): #printing the selected individuals
    Chromosome.describe(SELECTION[i])



Selected Individuals:
ID=#6, Fitness=6, 
Genes=
[0 1 0 1 1 1 1 0 1 0 0]
ID=#7, Fitness=8, 
Genes=
[0 1 0 0 1 1 1 1 1 1 1]
ID=#8, Fitness=9, 
Genes=
[1 1 1 0 1 1 1 1 1 1 0]


## <a id='tournament-select'>Tournament Selection</a>

Tournament selection involves running several "tournaments" among a few individuals (or "chromosomes") chosen at random from the population. The winner of each tournament (the one with the best fitness) is selected for crossover. Selection pressure, a probabilistic measure of a chromosome's likelihood of participation in the tournament based on the participant selection pool size, is easily adjusted by changing the tournament size. The reason is that if the tournament size is larger, weak individuals have a smaller chance to be selected, because, if a weak individual is selected to be in a tournament, there is a higher probability that a stronger individual is also in that tournament. This is the pseudo code that we use to implement tournament selection:

```
Choose k (the tournament size) individuals from the population at random.
Choose the best individual from the tournament with probability p ((1-p) someone random).
Repeat until the required number of selected individuals is met.
```

A 1-way tournament (k = 1) selection is equivalent to random selection. There are two variants of the selection: with and without replacement. The variant without replacement guarantees that when selecting N individuals from a population of N elements, each individual participates in exactly k tournaments. Note that depending on the number of elements selected, selection without replacement does not guarantee that no individual is selected more than once. It just guarantees that each individual has an equal chance of participating in the same number of tournaments. 


Tournament selection has several benefits over alternative selection methods for genetic algorithms (for example, fitness proportionate selection and reward-based selection): it is efficient to code, works on parallel architectures, and allows the selection pressure to be easily adjusted. 


In [49]:
def tournament_selection(selection_size, tournament_size, prob, pop):
    """
    This function takes a population, selects a group of chromosomes within,
    and returns the fittest one inside with probability prob.
    selection_size: Number of individuals to be selected within the population.
    tournament_size: Number of individuals in each tournament (bigger size means 
    more selection pressure)
    prob: The probability that the best individual in the tournament group is selected (also affects 
    the selection pressure)
    pop: The population which we want to select a number of individuals among them. 
    """  
    pop_size = len(pop) # size of the population
    assert selection_size <= pop_size, "Selection size can't be greater than the population size."
    group = [] # group of individuals participating in the tournament
    select = [] # final selected individuals

    assert tournament_size < pop_size, "Tournament size must be less than the population size."

    for _ in range(selection_size):
        
        # filling the group with random individuals 
        # notice that the selection is not unique here (an individual can be 
        # picked several times in a group or tournament)
        # for unique selection, use sample method from random library
        for _ in range(tournament_size):
            group.append(pop[np.random.randint(0, pop_size)])

        # choosing an individual from the group
        sorted_group = pop_sort(group) # sorting the group based on fitness
        # if prob is greater than random number
        if np.random.rand() < prob: 
            # then choose the best individual in the group
            individual = sorted_group[-1:][0]
        else:
            # otherwise, choose someone at random from the group
            individual = group[np.random.randint(0, tournament_size)]

        select.append(individual)
            
    return select


POP = []
chrom0 = np.array([0,1,1,0,1,0,0,0,0,1,0])
chrom1 = np.array([0,1,0,0,0,0,0,0,1,0,0])
chrom2 = np.array([0,1,0,0,0,0,1,0,0,1,0])
chrom3 = np.array([0,1,0,0,1,0,1,0,0,1,0])
chrom4 = np.array([0,0,1,0,1,0,0,1,0,1,0])
chrom5 = np.array([0,1,0,0,0,1,0,1,0,1,0])
chrom6 = np.array([0,1,0,1,1,1,1,0,1,0,0])
chrom7 = np.array([0,1,0,0,1,1,1,1,1,1,1])
chrom8 = np.array([1,1,1,0,1,1,1,1,1,1,0])
chrom9 = np.array([0,0,0,0,0,0,0,1,0,1,0])

POP.append(Chromosome(chrom0, id_= 0, fitness = fitness_function(chrom0)))
POP.append(Chromosome(chrom1, id_= 1, fitness = fitness_function(chrom1)))
POP.append(Chromosome(chrom2, id_= 2, fitness = fitness_function(chrom2)))
POP.append(Chromosome(chrom3, id_= 3, fitness = fitness_function(chrom3)))
POP.append(Chromosome(chrom4, id_= 4, fitness = fitness_function(chrom4)))
POP.append(Chromosome(chrom5, id_= 5, fitness = fitness_function(chrom5)))
POP.append(Chromosome(chrom6, id_= 6, fitness = fitness_function(chrom6)))
POP.append(Chromosome(chrom7, id_= 7, fitness = fitness_function(chrom7)))
POP.append(Chromosome(chrom8, id_= 8, fitness = fitness_function(chrom8)))
POP.append(Chromosome(chrom9, id_= 9, fitness = fitness_function(chrom9)))

# print("\nThe Population:")
# print("========================================")
# for i in range(len(POP)): #printing the population
#     Chromosome.describe(POP[i])

SELECTION = tournament_selection(3, 4, 0.5, POP)

print("\nSelected Individuals:")
print("========================================")
for i in range(len(SELECTION)): #printing the selected individuals
    Chromosome.describe(SELECTION[i])



Selected Individuals:
ID=#7, Fitness=8, 
Genes=
[0 1 0 0 1 1 1 1 1 1 1]
ID=#7, Fitness=8, 
Genes=
[0 1 0 0 1 1 1 1 1 1 1]
ID=#1, Fitness=2, 
Genes=
[0 1 0 0 0 0 0 0 1 0 0]


## <a id='self-adapt-tournament-select'>Self-Adaptive Tournament Selection</a>

**Self-Adaptive Tournament Selection** is an extension of the tournament selection method, which is a popular selection method in genetic algorithms. In Self-Adaptive Tournament Selection, the size of the tournament is not fixed, but rather it is determined by the population itself. <span style="color:#6699EF">The size of the tournament is adjusted based on the fitness of the individuals in the population. If the population is diverse, the tournament size is increased to allow weaker individuals to have a chance to be selected. If the population is homogeneous, the tournament size is decreased to increase the selection pressure.</span>

Self-Adaptive Tournament Selection has been shown to be effective in improving the performance of genetic algorithms on a range of fitness landscapes. 



In [50]:
import random

def self_adaptive_tournament_selection(selection_size, prob, population):
    """
    selection_size: Number of individuals to be selected within the population.
    prob: The probability that the best individual in the tournament group is selected (also affects 
    the selection pressure)
    population: The population which we want to select a number of individuals among them. 
    """  
    pop_size = len(population)
    assert selection_size <= pop_size, "Selection size can't be greater than the population size."
    diversity = calculate_diversity(population)
    tournament_size = calculate_tournament_size(pop_size, diversity)
    selected_individuals = []
    for _ in range(selection_size):
        tournament = select_random_individuals(population, tournament_size)
        winner = select_winner(tournament, prob)
        selected_individuals.append(winner)
    return selected_individuals


def calculate_diversity(population):
    """
    Calculate the diversity of the population can be done using various methods 
    such as clustering or entropy.
    population: The population which we want to select a number of individuals among them.
    """
    # Calculate the average fitness of the population
    avg_fitness = sum(individual.fitness for individual in population) / len(population)
    # Calculate the diversity of the population
    max_fitness = max(individual.fitness for individual in population)
    min_fitness = min(individual.fitness for individual in population)
    fitness_range = max_fitness - min_fitness
    diversity = sum(abs(individual.fitness - avg_fitness) for individual in population) / (len(population) * fitness_range / 2)

    return diversity


def calculate_tournament_size(pop_size, diversity):
    # Calculate the tournament size based on the diversity of the population
    # For example, if the population is diverse, increase the tournament size
    # If the population is homogeneous, decrease the tournament size
    return int(2 + (pop_size - 2) * diversity)

def select_random_individuals(population, tournament_size):
    # Select a random subset of unique individuals from the population
    # The size of the subset is equal to the tournament size
    assert tournament_size < len(population), "Tournament size must be less than the population size."
    return random.sample(population, tournament_size)

def select_winner(tournament, prob):
    # Select the winner of the tournament
    # This can be done using various methods such as fitness proportionate selection 
    # or rank-based selection
    tournament_size = len(tournament)
    
    # if prob is greater than random number
    if np.random.rand() < prob: 
        # sorting the group based on fitness
        sorted_tournament = pop_sort(tournament) 
        # then choose the best individual in the group
        return sorted_tournament[-1:][0]

    # otherwise, choose someone at random from the group (tournament)
    return tournament[np.random.randint(0, tournament_size)]



POP = []
chrom0 = np.array([0,1,1,0,1,0,0,0,0,1,0])
chrom1 = np.array([0,1,0,0,0,0,0,0,1,0,0])
chrom2 = np.array([0,1,0,0,0,0,1,0,0,1,0])
chrom3 = np.array([0,1,0,0,1,0,1,0,0,1,0])
chrom4 = np.array([0,0,1,0,1,0,0,1,0,1,0])
chrom5 = np.array([0,1,0,0,0,1,0,1,0,1,0])
chrom6 = np.array([0,1,0,1,1,1,1,0,1,0,0])
chrom7 = np.array([0,1,0,0,1,1,1,1,1,1,1])
chrom8 = np.array([1,1,1,0,1,1,1,1,1,1,0])
chrom9 = np.array([0,0,0,0,0,0,0,1,0,1,0])

POP.append(Chromosome(chrom0, id_= 0, fitness = fitness_function(chrom0)))
POP.append(Chromosome(chrom1, id_= 1, fitness = fitness_function(chrom1)))
POP.append(Chromosome(chrom2, id_= 2, fitness = fitness_function(chrom2)))
POP.append(Chromosome(chrom3, id_= 3, fitness = fitness_function(chrom3)))
POP.append(Chromosome(chrom4, id_= 4, fitness = fitness_function(chrom4)))
POP.append(Chromosome(chrom5, id_= 5, fitness = fitness_function(chrom5)))
POP.append(Chromosome(chrom6, id_= 6, fitness = fitness_function(chrom6)))
POP.append(Chromosome(chrom7, id_= 7, fitness = fitness_function(chrom7)))
POP.append(Chromosome(chrom8, id_= 8, fitness = fitness_function(chrom8)))
POP.append(Chromosome(chrom9, id_= 9, fitness = fitness_function(chrom9)))

# print("\nThe Population:")
# print("========================================")
# for i in range(len(POP)): #printing the population
#     Chromosome.describe(POP[i])

SELECTION = self_adaptive_tournament_selection(3, 0.5, POP)


print("\nSelected Individuals:")
print("========================================")
for i in range(len(SELECTION)): #printing the selected individuals
    Chromosome.describe(SELECTION[i])



Selected Individuals:
ID=#8, Fitness=9, 
Genes=
[1 1 1 0 1 1 1 1 1 1 0]
ID=#0, Fitness=4, 
Genes=
[0 1 1 0 1 0 0 0 0 1 0]
ID=#2, Fitness=3, 
Genes=
[0 1 0 0 0 0 1 0 0 1 0]


In the above implementation, `population` is a list of individuals, where each individual is an object with a `fitness` attribute. The `calculate_diversity` function calculates the diversity of the population, which is used to determine the tournament size. In this implementation, max_fitness and min_fitness are the maximum and minimum fitness values in the population, respectively. fitness_range is the range of the fitness values, and is equal to max_fitness - min_fitness. The diversity score is then normalized by dividing by fitness_range / 2, which is the maximum possible diversity score. 
The `calculate_tournament_size` function calculates the tournament size based on the diversity of the population. The reason for adding 2 in the tournament size calculation is to ensure that the tournament size is always greater than or equal to 2. This is because a tournament with only one individual is equivalent to random selection, and a tournament with no individuals is not possible. 
The `select_random_individuals` function selects a random subset of individuals from the population, and the `select_winner` function selects the winner of the tournament based on their fitness value.

## <a id='boltzmann-select'>Boltzmann Selection</a>

Boltzmann selection is a selection mechanism in evolutionary algorithms that thermodynamically controls the selection pressure using principles from simulated annealing. The temperature controls the rate of selection according to a preset schedule, and it starts out high, which means that the selection pressure is low. By the passage of the time, the selection pressure will increase and the selection will be biased towards individuals with better fitnesses. Boltzmann selection mechanisms can be used to indefinitely prolong an evolutionary algorithm's search to locate better final solutions.


In [51]:
def boltzmann_selection(selection_size, pop): 
    """
    In this method, the function which enforces selection pressure is linear (by the variable j).
    selection_size: Number of individuals to be selected within the population.
    pop: The population which we want to select a number of individuals among them
    """ 
    pop_size = len(pop) # size of the population
    assert selection_size <= pop_size, "Selection size can't be greater than the population size."
    probs = [0.0]*pop_size
    select = []    

    #The probabilities of selections will change everytime before picking an individual
    for j in range(selection_size): 
        for i in range(pop_size): 
            #calculating the probability of selection for each individual
            probs[i] = round(abs(1/(1 + np.exp(-fitness_function(pop[i].genes)/(j + 1)))), 3)
            
        select.append(random.choices(pop, probs, k = 1))       
    
    flat_list = [item for sublist in select for item in sublist]

    return flat_list


POP = []
chrom0 = np.array([0,1,1,0,1,0,0,0,0,1,0])
chrom1 = np.array([0,1,0,0,0,0,0,0,1,0,0])
chrom2 = np.array([0,1,0,0,0,0,1,0,0,1,0])
chrom3 = np.array([0,1,0,0,1,0,1,0,0,1,0])
chrom4 = np.array([0,0,1,0,1,0,0,1,0,1,0])
chrom5 = np.array([0,1,0,0,0,1,0,1,0,1,0])
chrom6 = np.array([0,1,0,1,1,1,1,0,1,0,0])
chrom7 = np.array([0,1,0,0,1,1,1,1,1,1,1])
chrom8 = np.array([1,1,1,0,1,1,1,1,1,1,0])
chrom9 = np.array([0,0,0,0,0,0,0,1,0,1,0])

POP.append(Chromosome(chrom0, id_= 0, fitness = fitness_function(chrom0)))
POP.append(Chromosome(chrom1, id_= 1, fitness = fitness_function(chrom1)))
POP.append(Chromosome(chrom2, id_= 2, fitness = fitness_function(chrom2)))
POP.append(Chromosome(chrom3, id_= 3, fitness = fitness_function(chrom3)))
POP.append(Chromosome(chrom4, id_= 4, fitness = fitness_function(chrom4)))
POP.append(Chromosome(chrom5, id_= 5, fitness = fitness_function(chrom5)))
POP.append(Chromosome(chrom6, id_= 6, fitness = fitness_function(chrom6)))
POP.append(Chromosome(chrom7, id_= 7, fitness = fitness_function(chrom7)))
POP.append(Chromosome(chrom8, id_= 8, fitness = fitness_function(chrom8)))
POP.append(Chromosome(chrom9, id_= 9, fitness = fitness_function(chrom9)))

# print("\nThe Population:")
# print("========================================")
# for i in range(len(POP)): #printing the population
#     Chromosome.describe(POP[i])

SELECTION = boltzmann_selection(3, POP)

print("\nSelected Individuals:")
print("========================================")
for i in range(len(SELECTION)): #printing the selected individuals
    Chromosome.describe(SELECTION[i])



Selected Individuals:
ID=#2, Fitness=3, 
Genes=
[0 1 0 0 0 0 1 0 0 1 0]
ID=#9, Fitness=2, 
Genes=
[0 0 0 0 0 0 0 1 0 1 0]
ID=#7, Fitness=8, 
Genes=
[0 1 0 0 1 1 1 1 1 1 1]


## <a id='proportional-select'>Proportional Selection</a>
In Proportional Selection, each individual has the probability of `fitness(x(i)) / total_fitnesses`, to be selected (the selection is biased towards individuals with better fitnesses), where `x(i)` is the individual and `total_fitnesses` is sum of the fitnesses of all the individuals in the population.

In [52]:
def proportional_selection(selection_size, pop): 
    """
    selection_size: Number of individuals to be selected within the population.
    pop: The population which we want to select a number of individuals among them
    """  
    pop_size = len(pop) # size of the population
    assert selection_size <= pop_size, "Selection size can't be greater than the population size."
    total_fitnesses = 0.0
    probs = [0.0]*pop_size
    select = []

    # calculating the sum of fitnesses of the whole population
    for i in range(pop_size): 
        total_fitnesses += pop[i].fitness

    # calculating the probability of selection for each individual
    for i in range(pop_size): 
        probs[i] = round(abs(pop[i].fitness/total_fitnesses), 3)

    select = random.choices(pop, probs, k = selection_size)

    return select


POP = []
chrom0 = np.array([0,1,1,0,1,0,0,0,0,1,0])
chrom1 = np.array([0,1,0,0,0,0,0,0,1,0,0])
chrom2 = np.array([0,1,0,0,0,0,1,0,0,1,0])
chrom3 = np.array([0,1,0,0,1,0,1,0,0,1,0])
chrom4 = np.array([0,0,1,0,1,0,0,1,0,1,0])
chrom5 = np.array([0,1,0,0,0,1,0,1,0,1,0])
chrom6 = np.array([0,1,0,1,1,1,1,0,1,0,0])
chrom7 = np.array([0,1,0,0,1,1,1,1,1,1,1])
chrom8 = np.array([1,1,1,0,1,1,1,1,1,1,0])
chrom9 = np.array([0,0,0,0,0,0,0,1,0,1,0])

POP.append(Chromosome(chrom0, id_= 0, fitness = fitness_function(chrom0)))
POP.append(Chromosome(chrom1, id_= 1, fitness = fitness_function(chrom1)))
POP.append(Chromosome(chrom2, id_= 2, fitness = fitness_function(chrom2)))
POP.append(Chromosome(chrom3, id_= 3, fitness = fitness_function(chrom3)))
POP.append(Chromosome(chrom4, id_= 4, fitness = fitness_function(chrom4)))
POP.append(Chromosome(chrom5, id_= 5, fitness = fitness_function(chrom5)))
POP.append(Chromosome(chrom6, id_= 6, fitness = fitness_function(chrom6)))
POP.append(Chromosome(chrom7, id_= 7, fitness = fitness_function(chrom7)))
POP.append(Chromosome(chrom8, id_= 8, fitness = fitness_function(chrom8)))
POP.append(Chromosome(chrom9, id_= 9, fitness = fitness_function(chrom9)))

# print("\nThe Population:")
# print("========================================")
# for i in range(len(POP)): #printing the population
#     Chromosome.describe(POP[i])

SELECTION = proportional_selection(3, POP)

print("\nSelected Individuals:")
print("========================================")
for i in range(len(SELECTION)): #printing the selected individuals
    Chromosome.describe(SELECTION[i])



Selected Individuals:
ID=#0, Fitness=4, 
Genes=
[0 1 1 0 1 0 0 0 0 1 0]
ID=#9, Fitness=2, 
Genes=
[0 0 0 0 0 0 0 1 0 1 0]
ID=#4, Fitness=4, 
Genes=
[0 0 1 0 1 0 0 1 0 1 0]


## <a id='fps-select'>Fitness Proportionate Selection (FPS)</a>

In **Fitness Proportionate Selection (FPS)**, also known as **Roulette Wheel Selection (RWS)**, the fitness function assigns a fitness score to each possible solution or chromosome. The fitness score is then used to associate a probability of selection with each individual chromosome. The probability of selection for an individual chromosome is proportional to its fitness score.  


For implementation, just like proportional selection, each individual has the probability of `fitness(x(i)) / total_fitnesses` to be selected, but this time we use a roulette wheel to select the individuals instead of the `choices` function in the `random` library.


> The following steps are involved in the FPS algorithm:
> 1. Calculate the fitness score of each chromosome in the population.
> 2. Calculate the sum of all fitness scores.
> 3. Calculate the probability of selection for each chromosome by dividing its fitness score by the sum of all fitness scores.
> 4. Generate a random number between 0 and 1.
> 5. Select the chromosome whose probability of selection is greater than or equal to the random number generated in step 4.
> 6. This process is repeated until the desired number of chromosomes is selected for recombination.

<span style="color:#BB6644">FPS is a popular selection method because it allows weaker solutions to survive the selection process, albeit with a lower probability of selection. </span> Other selection techniques, such as **stochastic universal sampling** or **tournament selection**, are also used in practice.


In [53]:
def roulette_wheel_selection(selection_size, pop):
    """
    selection_size: Number of individuals to be selected within the population.
    pop: The population which we want to select a number of individuals among them
    """  
    pop_size = len(pop) # size of the population
    assert selection_size <= pop_size, "Selection size can't be greater than the population size."
    total_fitnesses = 0.0
    probs = [0.0]*pop_size
    select = []
    wheel = []
    sums = 0 # for computing the cumulative probabilities (the Roulette wheel)

    # calculating the sum of fitnesses of the whole population
    for i in range(pop_size): 
        total_fitnesses += pop[i].fitness

    # calculating the probability of selection for each individual and also the Roulette wheel
    for i in range(pop_size): 
        probs[i] = abs(pop[i].fitness / total_fitnesses)
        sums += probs[i]
        wheel.append(sums)

  
    print("The Roulette wheel is:\n", wheel)


    #picking the individuals from the pool
    for i in range(selection_size): 
        chosen = 0 # the index of the chosen chromosome
        random_number = np.random.uniform(low=0.0, high=1.0) 
        for j in range(len(wheel)):
            if random_number <= wheel[j]:
                chosen = j 
                break

        print("Generated random number: ", random_number)
        print("The id of the chosen individual: ", chosen)
        select.append(pop[chosen])

    return select


POP = []
chrom0 = np.array([0,1,1,0,1,0,0,0,0,1,0])
chrom1 = np.array([0,1,0,0,0,0,0,0,1,0,0])
chrom2 = np.array([0,1,0,0,0,0,1,0,0,1,0])
chrom3 = np.array([0,1,0,0,1,0,1,0,0,1,0])
chrom4 = np.array([0,0,1,0,1,0,0,1,0,1,0])
chrom5 = np.array([0,1,0,0,0,1,0,1,0,1,0])
chrom6 = np.array([0,1,0,1,1,1,1,0,1,0,0])
chrom7 = np.array([0,1,0,0,1,1,1,1,1,1,1])
chrom8 = np.array([1,1,1,0,1,1,1,1,1,1,0])
chrom9 = np.array([0,0,0,0,0,0,0,1,0,1,0])

POP.append(Chromosome(chrom0, id_= 0, fitness = fitness_function(chrom0)))
POP.append(Chromosome(chrom1, id_= 1, fitness = fitness_function(chrom1)))
POP.append(Chromosome(chrom2, id_= 2, fitness = fitness_function(chrom2)))
POP.append(Chromosome(chrom3, id_= 3, fitness = fitness_function(chrom3)))
POP.append(Chromosome(chrom4, id_= 4, fitness = fitness_function(chrom4)))
POP.append(Chromosome(chrom5, id_= 5, fitness = fitness_function(chrom5)))
POP.append(Chromosome(chrom6, id_= 6, fitness = fitness_function(chrom6)))
POP.append(Chromosome(chrom7, id_= 7, fitness = fitness_function(chrom7)))
POP.append(Chromosome(chrom8, id_= 8, fitness = fitness_function(chrom8)))
POP.append(Chromosome(chrom9, id_= 9, fitness = fitness_function(chrom9)))

# print("\nThe Population:")
# print("========================================")
# for i in range(len(POP)): #printing the population
#     Chromosome.describe(POP[i])

SELECTION = roulette_wheel_selection(3, POP)

print("\nSelected Individuals:")
print("========================================")
for i in range(len(SELECTION)): #printing the selected individuals
    Chromosome.describe(SELECTION[i])


The Roulette wheel is:
 [0.08695652173913043, 0.13043478260869565, 0.19565217391304346, 0.2826086956521739, 0.3695652173913043, 0.45652173913043476, 0.5869565217391304, 0.7608695652173912, 0.9565217391304347, 0.9999999999999999]
Generated random number:  0.20089608510362966
The id of the chosen individual:  3
Generated random number:  0.4549140793816985
The id of the chosen individual:  5
Generated random number:  0.9207184343795998
The id of the chosen individual:  8

Selected Individuals:
ID=#3, Fitness=4, 
Genes=
[0 1 0 0 1 0 1 0 0 1 0]
ID=#5, Fitness=4, 
Genes=
[0 1 0 0 0 1 0 1 0 1 0]
ID=#8, Fitness=9, 
Genes=
[1 1 1 0 1 1 1 1 1 1 0]


## <a id='rwsa-select'>Roulette Wheel Selection with Stochastic Acceptance (RWSA)</a>

**Roulette Wheel Selection with Stochastic Acceptance** is an extension of the **Roulette Wheel Selection (RWS)** method, which is also known as **Fitness Proportionate Selection (FPS)**. 

In RWS, the probability of selecting a chromosome is proportional to its fitness score. However, this method can lead to premature convergence, where the population converges to a suboptimal solution too quickly. RWS with Stochastic Acceptance (RWSA) addresses this issue by introducing a stochastic element to the selection process.  



The probability that the individual selected in an unspecified number of attempts will be the i-th individual is calculated as below:

`prob[i] = (fitness(chromosome[i]) / (pop_size*maximum_fitness)) * (1 + q + q^2 + q^3 + ...)`

Based on Maclaurin series, the geometrical series `1 + q + q^2 + q^3 + ...` is convergent when `0 < q < 1` and is equal to `1 / (1 - q)`, which gives:

`prob[i] = (fitness(chromosome[i]) / (pop_size*maximum_fitness)) * (1 / (1 - q))`

where `q` is the rejection probability. In RWSA, the rejection probability is the probability that a chromosome with a fitness score below a certain threshold is rejected during the selection process 1.


In **Roulette Wheel Selection with Stochastic Acceptance (RWSA)**, the **rejection probability** is the probability that a chromosome with a fitness score below a certain threshold is rejected during the selection process. In our implementation rejection probability is calculated as follows: 

`rejection_probability = 1 - (average_fitness / maximum_fitness)`

where `average_fitness` is the mathematical average of the fitnesses of the individuals in the population. 

<span style="color:#55EE99">
RWSA is a popular selection method because it allows weaker solutions to survive the selection process, albeit with a lower probability of selection. This can help to prevent premature convergence and improve the diversity of the population. </span>

In [54]:
def roulette_wheel_selection_with_stochastic_acceptance(selection_size, pop): 
    """
    selection_size: Number of individuals to be selected within the population.
    pop: The population which we want to select a number of individuals among them.
    """  
    pop_size = len(pop) # size of the population
    assert selection_size <= pop_size, "Selection size can't be greater than the population size."
    total_fitnesses = 0.0
    probs = [0.0]*pop_size
    select = []

    # finding the maximum fitness
    maximum_fitness = 0
    for i in range(pop_size): 
        if pop[i].fitness > maximum_fitness:
            maximum_fitness = pop[i].fitness

    # calculating the sum of fitnesses of the whole population
    for i in range(pop_size): 
        total_fitnesses += pop[i].fitness

    average_fitness = abs(total_fitnesses / pop_size)
    # rejection probability
    rejection_probability = 1 - (average_fitness / maximum_fitness)

    #calculating the probability of selection for each individual 
    for i in range(pop_size): 
        probs[i] = abs((fitness_function(pop[i].genes)/(pop_size*maximum_fitness))*(1/(1 - rejection_probability)))
        
    select = random.choices(pop, probs, k = selection_size)

    return select




POP = []
chrom0 = np.array([0,1,1,0,1,0,0,0,0,1,0])
chrom1 = np.array([0,1,0,0,0,0,0,0,1,0,0])
chrom2 = np.array([0,1,0,0,0,0,1,0,0,1,0])
chrom3 = np.array([0,1,0,0,1,0,1,0,0,1,0])
chrom4 = np.array([0,0,1,0,1,0,0,1,0,1,0])
chrom5 = np.array([0,1,0,0,0,1,0,1,0,1,0])
chrom6 = np.array([0,1,0,1,1,1,1,0,1,0,0])
chrom7 = np.array([0,1,0,0,1,1,1,1,1,1,1])
chrom8 = np.array([1,1,1,0,1,1,1,1,1,1,0])
chrom9 = np.array([0,0,0,0,0,0,0,1,0,1,0])

POP.append(Chromosome(chrom0, id_= 0, fitness = fitness_function(chrom0)))
POP.append(Chromosome(chrom1, id_= 1, fitness = fitness_function(chrom1)))
POP.append(Chromosome(chrom2, id_= 2, fitness = fitness_function(chrom2)))
POP.append(Chromosome(chrom3, id_= 3, fitness = fitness_function(chrom3)))
POP.append(Chromosome(chrom4, id_= 4, fitness = fitness_function(chrom4)))
POP.append(Chromosome(chrom5, id_= 5, fitness = fitness_function(chrom5)))
POP.append(Chromosome(chrom6, id_= 6, fitness = fitness_function(chrom6)))
POP.append(Chromosome(chrom7, id_= 7, fitness = fitness_function(chrom7)))
POP.append(Chromosome(chrom8, id_= 8, fitness = fitness_function(chrom8)))
POP.append(Chromosome(chrom9, id_= 9, fitness = fitness_function(chrom9)))

# print("\nThe Population:")
# print("========================================")
# for i in range(len(POP)): #printing the population
#     Chromosome.describe(POP[i])

SELECTION = roulette_wheel_selection_with_stochastic_acceptance(3, POP)

print("\nSelected Individuals:")
print("========================================")
for i in range(len(SELECTION)): #printing the selected individuals
    Chromosome.describe(SELECTION[i])



Selected Individuals:
ID=#6, Fitness=6, 
Genes=
[0 1 0 1 1 1 1 0 1 0 0]
ID=#7, Fitness=8, 
Genes=
[0 1 0 0 1 1 1 1 1 1 1]
ID=#3, Fitness=4, 
Genes=
[0 1 0 0 1 0 1 0 0 1 0]


## <a id='sus-select'>Stochastic Universal Sampling Selection (SUS)</a>

Stochastic Universal Sampling (SUS) is a development of fitness proportionate selection (FPS) which exhibits no bias and minimal spread. In SUS, a single random value is used to sample all of the solutions by choosing them at evenly spaced intervals. This gives weaker members of the population (according to their fitness) a chance to be chosen. Using a comb-like ruler, SUS starts from a small random number, and chooses the next candidates from the rest of population remaining, not allowing the fittest members to saturate the candidate space. The main difference between this selection and Roulette wheel selection is that it gives more opportunity to individual with lower fitnesses. SUS is a more efficient and less biased alternative to fitness proportionate selection (FPS).



In [55]:
def stochastic_universal_sampling_selection(selection_size, pop): 
    """
    In Stochastic Universal Sampling Selection (SUS), each individual has the 
    probability of `fitness(x(i))/total_fitnesses`, to be selected (the selection 
    is biased towards individuals with better fitnesses), where `x(i)` is the individual.
    selection_size: Number of individuals to be selected within the population.
    pop: The population which we want to select a number of individuals among them
    """  
    pop_size = len(pop) # size of the population
    assert selection_size <= pop_size, "Selection size can't be greater than the population size."
    total_fitnesses = 0.0
    probs = [0.0]*pop_size
    select = []
    wheel = []
    sums = 0

    # calculating the sum of fitnesses of the whole population
    for i in range(pop_size): 
        total_fitnesses += pop[i].fitness

    # calculating the probability of selection for each individual and also the Roulette wheel
    for i in range(pop_size): 
        probs[i] = abs(pop[i].fitness / total_fitnesses)
        sums += probs[i]
        wheel.append(sums)

    print("The Roulette wheel is:\n", wheel)

    # calculating the hands on the roulette wheel
    wheel_hands = [] 
    bias = 1.0/selection_size # the distance between the hands 
    random_number = np.random.uniform(low= 0.0, high = bias)
    wheel_hands.append(random_number)
    for i in range(selection_size - 1): 
        random_number += bias
        wheel_hands.append(random_number)

    # choosing the final individuals
    for i in range(selection_size):
        chosen = 0 # the index of the chosen chromosome
        for j in range(len(wheel)):
            if wheel_hands[i] <= wheel[j]:
                chosen = j
                break

        select.append(pop[chosen])

    print("The hands on the wheel:\n", wheel_hands)
    
    return select


POP = []
chrom0 = np.array([0,1,1,0,1,0,0,0,0,1,0])
chrom1 = np.array([0,1,0,0,0,0,0,0,1,0,0])
chrom2 = np.array([0,1,0,0,0,0,1,0,0,1,0])
chrom3 = np.array([0,1,0,0,1,0,1,0,0,1,0])
chrom4 = np.array([0,0,1,0,1,0,0,1,0,1,0])
chrom5 = np.array([0,1,0,0,0,1,0,1,0,1,0])
chrom6 = np.array([0,1,0,1,1,1,1,0,1,0,0])
chrom7 = np.array([0,1,0,0,1,1,1,1,1,1,1])
chrom8 = np.array([1,1,1,0,1,1,1,1,1,1,0])
chrom9 = np.array([0,0,0,0,0,0,0,1,0,1,0])

POP.append(Chromosome(chrom0, id_= 0, fitness = fitness_function(chrom0)))
POP.append(Chromosome(chrom1, id_= 1, fitness = fitness_function(chrom1)))
POP.append(Chromosome(chrom2, id_= 2, fitness = fitness_function(chrom2)))
POP.append(Chromosome(chrom3, id_= 3, fitness = fitness_function(chrom3)))
POP.append(Chromosome(chrom4, id_= 4, fitness = fitness_function(chrom4)))
POP.append(Chromosome(chrom5, id_= 5, fitness = fitness_function(chrom5)))
POP.append(Chromosome(chrom6, id_= 6, fitness = fitness_function(chrom6)))
POP.append(Chromosome(chrom7, id_= 7, fitness = fitness_function(chrom7)))
POP.append(Chromosome(chrom8, id_= 8, fitness = fitness_function(chrom8)))
POP.append(Chromosome(chrom9, id_= 9, fitness = fitness_function(chrom9)))

# print("\nThe Population:")
# print("========================================")
# for i in range(len(POP)): #printing the population
#     Chromosome.describe(POP[i])

SELECTION = stochastic_universal_sampling_selection(3, POP)

print("\nSelected Individuals:")
print("========================================")
for i in range(len(SELECTION)): #printing the selected individuals
    Chromosome.describe(SELECTION[i])


The Roulette wheel is:
 [0.08695652173913043, 0.13043478260869565, 0.19565217391304346, 0.2826086956521739, 0.3695652173913043, 0.45652173913043476, 0.5869565217391304, 0.7608695652173912, 0.9565217391304347, 0.9999999999999999]
The hands on the wheel:
 [0.23512768455603777, 0.5684610178893711, 0.9017943512227045]

Selected Individuals:
ID=#3, Fitness=4, 
Genes=
[0 1 0 0 1 0 1 0 0 1 0]
ID=#6, Fitness=6, 
Genes=
[0 1 0 1 1 1 1 0 1 0 0]
ID=#8, Fitness=9, 
Genes=
[1 1 1 0 1 1 1 1 1 1 0]


## <a id='linear-ranking-select'>Linear Ranking Selection</a>

In **Linear Ranking Selection**, the individuals in the population are first sorted according to their fitness values, and then ranks are assigned to them based on their position in the sorted list. The best individual is assigned rank `N`, where `N` is the size of the population, and the worst individual is assigned rank `1`. 

The selection probability is then assigned linearly to the individuals according to their ranks. The probability of selecting the `i`th individual is given by:

```
p(i) = (2 - s) / N + 2 * (i - 1) * (s - 1) / (N * (N - 1))
```

where `s` is a selection pressure parameter between 1 and 2, and `N` is the size of the population. 


The selection pressure parameter `s` is typically between 1 and 2 because this range provides a good balance between exploration and exploitation of the search space. A value of `s` close to 1 gives more weight to weaker individuals, which can help to maintain diversity in the population and prevent premature convergence. A value of `s` close to 2 gives more weight to fitter individuals, which can help to converge towards the optimal solution more quickly. <span style="color:#88BBEE"> The optimal value of `s` depends on the problem being solved and may need to be determined empirically. You could start with 1 and move closer to 2 as the search goes on to move from exploration to exploitation. </span> For our implementation here, we set `s = 1.5` to balance the two. 


Linear Ranking Selection is a popular selection method because it allows for a balance between exploration and exploitation of the search space. By assigning higher probabilities to better individuals, it encourages convergence towards the optimal solution. However, by also assigning non-zero probabilities to weaker individuals, it maintains diversity in the population and prevents premature convergence.




In [56]:
def linear_ranking_selection(selection_size, select_press, pop):
    """
    selection_size: Number of individuals to be selected within the population.
    select_press: The selection pressure when selecting individuals (between 1 and 2)
    pop: The population which we want to select a number of individuals among them
    """ 
    pop_size = len(pop) # size of the population
    assert selection_size <= pop_size, "Selection size can't be greater than the population size."
    sorted_pop = pop_sort(pop)
    select = []

    # What we do here is instead of determining the ranks for an unsorted population,
    # we sort the population in ascending order, calculate the probabilities based on 
    # ranks (basically the indices of the sorted population starting from 1) and then
    # pick the final individuals from the list of sorted population instead of the list 
    # of population. 

    # calculating the ranks (because we're choosing from the sorted population)
    ranks = np.arange(1, pop_size + 1)

    # Calculate the selection probability for each individual
    probs = (2 - select_press) / pop_size + 2 * (ranks - 1) * (select_press - 1) / (pop_size * (pop_size - 1))

    # select the final individuals based on the calculated probabilities
    select = random.choices(sorted_pop, probs, k = selection_size)

    return select





POP = []
chrom0 = np.array([0,1,1,0,1,0,0,0,0,1,0])
chrom1 = np.array([0,1,0,0,0,0,0,0,1,0,0])
chrom2 = np.array([0,1,0,0,0,0,1,0,0,1,0])
chrom3 = np.array([0,1,0,0,1,0,1,0,0,1,0])
chrom4 = np.array([0,0,1,0,1,0,0,1,0,1,0])
chrom5 = np.array([0,1,0,0,0,1,0,1,0,1,0])
chrom6 = np.array([0,1,0,1,1,1,1,0,1,0,0])
chrom7 = np.array([0,1,0,0,1,1,1,1,1,1,1])
chrom8 = np.array([1,1,1,0,1,1,1,1,1,1,0])
chrom9 = np.array([0,0,0,0,0,0,0,1,0,1,0])

POP.append(Chromosome(chrom0, id_= 0, fitness = fitness_function(chrom0)))
POP.append(Chromosome(chrom1, id_= 1, fitness = fitness_function(chrom1)))
POP.append(Chromosome(chrom2, id_= 2, fitness = fitness_function(chrom2)))
POP.append(Chromosome(chrom3, id_= 3, fitness = fitness_function(chrom3)))
POP.append(Chromosome(chrom4, id_= 4, fitness = fitness_function(chrom4)))
POP.append(Chromosome(chrom5, id_= 5, fitness = fitness_function(chrom5)))
POP.append(Chromosome(chrom6, id_= 6, fitness = fitness_function(chrom6)))
POP.append(Chromosome(chrom7, id_= 7, fitness = fitness_function(chrom7)))
POP.append(Chromosome(chrom8, id_= 8, fitness = fitness_function(chrom8)))
POP.append(Chromosome(chrom9, id_= 9, fitness = fitness_function(chrom9)))

# print("\nThe Population:")
# print("========================================")
# for i in range(len(POP)): #printing the population
#     Chromosome.describe(POP[i])

SELECTION = linear_ranking_selection(3, 1.5, POP)

print("\nSelected Individuals:")
print("========================================")
for i in range(len(SELECTION)): #printing the selected individuals
    Chromosome.describe(SELECTION[i])



Selected Individuals:
ID=#0, Fitness=4, 
Genes=
[0 1 1 0 1 0 0 0 0 1 0]
ID=#8, Fitness=9, 
Genes=
[1 1 1 0 1 1 1 1 1 1 0]
ID=#0, Fitness=4, 
Genes=
[0 1 1 0 1 0 0 0 0 1 0]


## <a id='exponential-ranking-select'>Exponential Ranking Selection</a>

In **Exponential Ranking Selection**, the individuals in the population are first sorted according to their fitness values, and then ranks are assigned to them based on their position in the sorted list. The best individual is assigned rank `N`, where `N` is the size of the population, and the worst individual is assigned rank `1`. 

The selection probability is then assigned exponentially to the individuals according to their ranks. The probability of selecting the `i`th individual is given by:

```
p(i) = c * (1 - exp(-r(i) / k))
```

where `c` is a scaling factor, `r(i)` is the rank of the `i`th individual, and `k` is a constant that controls the shape of the probability distribution.

<span style="color:#EE88AA"> The value of `c` determines the overall scale of the selection probabilities. A larger value of `c` gives higher probabilities to the fittest individuals, while a smaller value of `c` gives more weight to weaker individuals. The optimal value of `c` depends on the problem being solved and may need to be determined empirically.</span>



<span style="color:#AA88EE"> The value of `k` controls the shape of the probability distribution. A smaller value of `k` gives a more uniform distribution, while a larger value of `k` gives a more peaked distribution. The optimal value of `k` depends on the size of the population and the number of individuals being selected, and may need to be determined empirically.</span>



<span style="color:#77EEBB"> Changing the values of `c` and `k` can affect the performance of the algorithm by changing the balance between exploration and exploitation of the search space. In our implementation, we use `c=1.0` and `k=1.0` as default values for the scaling factor and the constant that controls the shape of the probability distribution, respectively. However, these values are not necessarily optimal for all problems.</span>



Exponential Ranking Selection is a popular selection method because it allows for a balance between exploration and exploitation of the search space. By assigning higher probabilities to better individuals, it encourages convergence towards the optimal solution. However, by also assigning non-zero probabilities to weaker individuals, it maintains diversity in the population and prevents premature convergence.



In [57]:
def exponential_ranking_selection(selection_size, pop, c=1.0, k=1.0): 
    """
    selection_size: Number of individuals to be selected within the population.
    pop: The population which we want to select a number of individuals among them.
    c: The scaling factor determining the overal scale of the selection probabilities.
    k: The constant that controls the shape of the probability distribution.
    """ 
    pop_size = len(pop) # size of the population
    assert selection_size <= pop_size, "Selection size can't be greater than the population size."
    sorted_pop = pop_sort(pop)
    select = []

    # What we do here is instead of determining the ranks for an unsorted population,
    # we sort the population in ascending order, calculate the probabilities based on 
    # ranks (basically the indices of the sorted population starting from 1) and then
    # pick the final individuals from the list of sorted population instead of the list 
    # of population. 

    # calculating the ranks (because we're choosing from the sorted population)
    ranks = np.arange(1, pop_size + 1)

    # Calculate the selection probability for each individual
    probs = c * (1 - np.exp(-ranks / k))

    # select the final individuals based on the calculated probabilities
    select = random.choices(sorted_pop, probs, k = selection_size)

    return select




POP = []
chrom0 = np.array([0,1,1,0,1,0,0,0,0,1,0])
chrom1 = np.array([0,1,0,0,0,0,0,0,1,0,0])
chrom2 = np.array([0,1,0,0,0,0,1,0,0,1,0])
chrom3 = np.array([0,1,0,0,1,0,1,0,0,1,0])
chrom4 = np.array([0,0,1,0,1,0,0,1,0,1,0])
chrom5 = np.array([0,1,0,0,0,1,0,1,0,1,0])
chrom6 = np.array([0,1,0,1,1,1,1,0,1,0,0])
chrom7 = np.array([0,1,0,0,1,1,1,1,1,1,1])
chrom8 = np.array([1,1,1,0,1,1,1,1,1,1,0])
chrom9 = np.array([0,0,0,0,0,0,0,1,0,1,0])

POP.append(Chromosome(chrom0, id_= 0, fitness = fitness_function(chrom0)))
POP.append(Chromosome(chrom1, id_= 1, fitness = fitness_function(chrom1)))
POP.append(Chromosome(chrom2, id_= 2, fitness = fitness_function(chrom2)))
POP.append(Chromosome(chrom3, id_= 3, fitness = fitness_function(chrom3)))
POP.append(Chromosome(chrom4, id_= 4, fitness = fitness_function(chrom4)))
POP.append(Chromosome(chrom5, id_= 5, fitness = fitness_function(chrom5)))
POP.append(Chromosome(chrom6, id_= 6, fitness = fitness_function(chrom6)))
POP.append(Chromosome(chrom7, id_= 7, fitness = fitness_function(chrom7)))
POP.append(Chromosome(chrom8, id_= 8, fitness = fitness_function(chrom8)))
POP.append(Chromosome(chrom9, id_= 9, fitness = fitness_function(chrom9)))

# print("\nThe Population:")
# print("========================================")
# for i in range(len(POP)): #printing the population
#     Chromosome.describe(POP[i])

SELECTION = exponential_ranking_selection(3, POP, 1.0, 1.0)

print("\nSelected Individuals:")
print("========================================")
for i in range(len(SELECTION)): #printing the selected individuals
    Chromosome.describe(SELECTION[i])



Selected Individuals:
ID=#0, Fitness=4, 
Genes=
[0 1 1 0 1 0 0 0 0 1 0]
ID=#1, Fitness=2, 
Genes=
[0 1 0 0 0 0 0 0 1 0 0]
ID=#4, Fitness=4, 
Genes=
[0 0 1 0 1 0 0 1 0 1 0]


### <a id='replace-strategy'>Replacement Strategies</a>
- Replace worst: replace offspring with the worst individual in current population.
- Replace random: replace offspring with a random individual in current population.
- Kill tournament: replace an offspring with the worst individual in n_ts, using tournament selection.
- Replace oldest: use FIFO strategy and replace offspring with the oldest individual in the current population.
- Conservative selection: combine FIFO replacement with a modified deterministic binary selection.
- Elitism: The best individual is excluded from selection.
- Parent-offspring: a selection strategy is used to decide whether an offspring replaces one of its own parents.

<span style="color:#3366FF">**Congratulations:** </span>
In the next article, we talk about recombination (crossover operators) in genetic algorithms.

## References 

1. Engelbrecht, A. P. (2007). Computational Intelligence: An Introduction (2nd ed.). John Wiley & Sons.

2. Selection (genetic algorithm). (n.d.). In Wikipedia. Retrieved December 9, 2023, from https://en.wikipedia.org/wiki/Selection_%28genetic_algorithm%29

3. Introduction To Genetic Algorithms. (n.d.). In IIT Guwahati. Retrieved December 9, 2023, from https://www.iitg.ac.in/rkbc/CE602/CE602/Genetic%20Algorithms.pdf

4. Genetic Algorithms - Parent Selection. (n.d.). In Online Tutorials Library. Retrieved December 9, 2023, from https://www.tutorialspoint.com/genetic_algorithms/genetic_algorithms_parent_selection.htm

5. Genetic Algorithms. (n.d.). In GeeksforGeeks. Retrieved December 9, 2023, from https://www.geeksforgeeks.org/genetic-algorithms/

6. Bing. (2023). Selection operator in genetic algorithms [Graphical artwork]. Generated by Bing AI, December 7, 2023, chat mode.

7. Boltzmann selection. (n.d.). In Evolutionary Computation 1. Taylor & Francis. Retrieved December 9, 2023, from https://www.taylorfrancis.com/chapters/edit/10.1201/9781482268713-33/boltzmann-selection

8. Selection (genetic algorithm). (n.d.). In Wikipedia. Retrieved December 9, 2023, from https://en.wikipedia.org/wiki/Selection_%28genetic_algorithm%29

9. Kita, H., & Narihisa, H. (2002). Entropy-Boltzmann selection in the genetic algorithms. IEEE Transactions on Evolutionary Computation, 6(1), 52-58. doi: 10.1109/4235.985692

10. De La Maza, M. (2010). The Boltzmann Selection Procedure 1. In The Practice of Simulated Annealing (pp. 69-78). CRC Press. Retrieved December 9, 2023, from https://www.taylorfrancis.com/chapters/edit/10.1201/9780429128332-6/boltzmann-selection-procedure-1-michael-de-la-maza

11. Selection (genetic algorithm). (n.d.). In Wikipedia. Retrieved December 9, 2023, from https://en.wikipedia.org/wiki/Selection_%28genetic_algorithm%29

12. Genetic Algorithms - Parent Selection. (n.d.). In Online Tutorials Library. Retrieved December 9, 2023, from https://www.tutorialspoint.com/genetic_algorithms/genetic_algorithms_parent_selection.htm

13. Roulette Selection in Genetic Algorithms. (n.d.). In Baeldung. Retrieved December 9, 2023, from https://www.baeldung.com/cs/genetic-algorithms-roulette-selection

14. How genetic algorithm is different from random selection and evaluation .... (n.d.). In Stack Overflow. Retrieved December 9, 2023, from https://stackoverflow.com/questions/24028270/how-genetic-algorithm-is-different-from-random-selection-and-evaluation-for-fitt

15. Truncation selection. (n.d.). In Wikipedia. Retrieved December 9, 2023, from https://en.wikipedia.org/wiki/Truncation_selection

16. Chapter 3. Selection Strategies & Elitism. (n.d.). In Uncommons. Retrieved December 9, 2023, from https://watchmaker.uncommons.org/manual/ch03.html

17. Selection (genetic algorithm). (n.d.). In Wikipedia. Retrieved December 9, 2023, from https://en.wikipedia.org/wiki/Selection_%28genetic_algorithm%29

18. Tournament selection. (n.d.). In Wikipedia. Retrieved December 9, 2023, from https://en.wikipedia.org/wiki/Tournament_selection

19. Tournament selection. (n.d.). In HandWiki. Retrieved December 9, 2023, from https://handwiki.org/wiki/Tournament_selection

20. tournament selection in genetic algorithm. (n.d.). In Stack Overflow. Retrieved December 9, 2023, from https://stackoverflow.com/questions/31933784/tournament-selection-in-genetic-algorithm

21. GeeksforGeeks. (n.d.). Tournament Selection (GA). Retrieved December 9, 2023, from https://www.geeksforgeeks.org/tournament-selection-ga/

22. Stochastic universal sampling. (n.d.). In Wikipedia. Retrieved December 9, 2023, from https://en.wikipedia.org/wiki/Stochastic_universal_sampling

23. Stochastic universal sampling. (n.d.). In wikidoc. Retrieved December 9, 2023, from https://www.wikidoc.org/index.php?title=Stochastic_universal_sampling

24. Jarrus, P. (2019, January 1). Stochastic Universal Sampling. Project Jarrus. Retrieved December 9, 2023, from https://blog.jarr.us/2019/01/stochastic-universal-sampling.html

25. Stochastic universal sampling. (n.d.). In Wikipedia. Retrieved December 9, 2023, from https://en.wikipedia.org/wiki/Stochastic_universal_sampling

26. Tournament selection. (n.d.). In Wikipedia. Retrieved December 9, 2023, from https://en.wikipedia.org/wiki/Tournament_selection

27. Gusz, E., & Kozma, B. (2006). Boosting Genetic Algorithms with Self-Adaptive Selection. In Proceedings of the 2006 IEEE Congress on Evolutionary Computation (pp. 1-8). doi: 10.1109/CEC.2006.1688325

28. Zoran, B. (n.d.). bpzoran/gadapt: Self-Adaptive Genetic Algorithm. GitHub. Retrieved December 9, 2023, from https://github.com/bpzoran/gadapt

29. Yang, S., & Ong, Y. S. (2017). Multi-objective Optimisation by Self-adaptive Evolutionary Algorithm with Stochastic Universal Sampling. In Proceedings of the 2017 IEEE Congress on Evolutionary Computation (pp. 1-8). doi: 10.1109/CEC.2017.7969384

30. Yang, S., & Ong, Y. S. (2017). Multi-objective Optimisation by Self-adaptive Evolutionary Algorithm with Stochastic Universal Sampling. In Proceedings of the 2017 IEEE Congress on Evolutionary Computation (pp. 1-8). doi: 10.1109/CEC.2017.7969384

31. Stack Overflow. (n.d.). tournament selection in genetic algorithm. Retrieved December 9, 2023, from https://stackoverflow.com/questions/31933784/tournament-selection-in-genetic-algorithm

32. Tournament selection. (n.d.). In Wikipedia. Retrieved December 9, 2023, from https://en.wikipedia.org/wiki/Tournament_selection

33. Zhang, Y., & Li, Y. (2022). Towards Self-Adaptive Pseudo-Label Filtering for Semi-Supervised Learning. arXiv preprint arXiv:2309.09774.

34. Fitness proportionate selection. (n.d.). In Wikipedia. Retrieved December 9, 2023, from https://en.wikipedia.org/wiki/Fitness_proportionate_selection

35. Genetic Algorithms - Parent Selection. (n.d.). In Online Tutorials Library. Retrieved December 9, 2023, from https://www.tutorialspoint.com/genetic_algorithms/genetic_algorithms_parent_selection.htm

36. Fitness proportionate selection. (n.d.). In HandWiki. Retrieved December 9, 2023, from https://handwiki.org/wiki/Fitness_proportionate_selection

37. Hancock, P. J. (1995). Chapter 3. In Practical Handbook of Genetic Algorithms: Volume II (pp. 29-42). CRC Press.

38. Eiben, A. E., & Smith, J. E. (2015). Roulette-wheel selection via stochastic acceptance. arXiv preprint arXiv:1109.3627.

39. Eiben, A. E., & Smith, J. E. (2015). Roulette-wheel selection via stochastic acceptance. arXiv preprint arXiv:1109.3627v1.

40. Eiben, A. E., & Smith, J. E. (2015). Roulette-wheel selection via stochastic acceptance. Archive.org. Retrieved December 9, 2023, from https://archive.org/details/arxiv-1109.3627

41. Eiben, A. E., & Smith, J. E. (2015). Roulette-wheel selection via stochastic acceptance. arXiv preprint arXiv:1109.3627.

42. Wang, J., & Chen, Y. (2012). A new method for ranking nodes in complex networks based on the fitness of the nodes. Physica A: Statistical Mechanics and its Applications, 391(4), 1569-1578. doi: 10.1016/j.physa.2011.12.004

43. Davies, R. B. (2020). Simulation - Lecture 3 - Rejection Sampling. University of Oxford. Retrieved December 9, 2023, from https://www.stats.ox.ac.uk/~rdavies/teaching/PartASSP/2020/lectures_latest/simulation_lecture3.pdf

44. Stack Overflow. (n.d.). Ranking Selection in Genetic Algorithm code. Retrieved December 9, 2023, from https://stackoverflow.com/questions/13659815/ranking-selection-in-genetic-algorithm-code

45. Stack Overflow. (n.d.). How to perform rank based selection in a genetic algorithm?. Retrieved December 9, 2023, from https://stackoverflow.com/questions/20290831/how-to-perform-rank-based-selection-in-a-genetic-algorithm

46. Chen, D. (n.d.). gaLRselection: Linear Ranking Selection in dchen49/GA: Variable Selection using Genetic Algorithms. Retrieved December 9, 2023, from https://rdrr.io/github/dchen49/GA/man/gaLRselection.html

47. Computer Science Stack Exchange. (2018). How is Rank Selection better than Random selection and RWS?. Retrieved December 9, 2023, from https://cs.stackexchange.com/questions/89886/how-is-rank-selection-better-than-random-selection-and-rws

48. Srinivas, M., & Patnaik, L. M. (1994). An analysis of linear ranking and binary tournament selection in genetic algorithms. IEEE Transactions on Evolutionary Computation, 1(3), 174-182. doi: 10.1109/4235.310205

49. University of Massachusetts Amherst. (n.d.). What is selection pressure in the context of natural selection? Retrieved December 9, 2023, from https://bcrc.bio.umass.edu/courses/spring2019/biol/biol312section2/content/what-selection-pressure-context-natural-selection

50. ScienceOxygen. (n.d.). What are selection pressures? [Answered!]. Retrieved December 9, 2023, from https://scienceoxygen.com/what-are-selection-pressures/

51. AllTheScience. (n.d.). What is Selection Pressure? (with pictures). Retrieved December 9, 2023, from https://www.allthescience.org/what-is-selection-pressure.htm

52. Biology LibreTexts. (n.d.). 12.11: Selective and Environmental Pressures. Retrieved December 9, 2023, from https://bio.libretexts.org/Courses/Lumen_Learning/Biology_for_Non_Majors_I_%28Lumen%29/12%3A_Theory_of_Evolution/12.11%3A_Selective_and_Environmental_Pressures

53. Chen, D. (n.d.). gaExpSelection: Exponential Ranking Selection in dchen49/GA: Variable Selection using Genetic Algorithms. Retrieved December 9, 2023, from https://rdrr.io/github/dchen49/GA/man/gaExpSelection.html

54. Stack Overflow. (n.d.). How to perform rank based selection in a genetic algorithm?. Retrieved December 9, 2023, from https://stackoverflow.com/questions/20290831/how-to-perform-rank-based-selection-in-a-genetic-algorithm

55. Selection (genetic algorithm). (n.d.). In Wikipedia. Retrieved December 9, 2023, from https://en.wikipedia.org/wiki/Selection_%28genetic_algorithm%29

56. Chen, D. (n.d.). gaExpSelection: Exponential Ranking Selection in dchen49/GA: Variable Selection using Genetic Algorithms. Retrieved December 9, 2023, from https://rdrr.io/github/dchen49/GA/man/gaExpSelection.html

57. Numerade. (n.d.). SOLVED:Geometric ranking (sometimes called exponential ranking) assumes that the probability of selecting the... Retrieved December 9, 2023, from https://www.numerade.com/questions/geometric-ranking-sometimes-called-exponential-ranking-assumes-that-the-probability-of-selecting-the/

58. Birmingham, U. o. (n.d.). Evolutionary Computation Selection. Retrieved December 9, 2023, from https://www.cs.bham.ac.uk/~szh/teaching/ec/Lecture7_SelectionSceheme.pdf

59. Hancock, P. J. (1995). Chapter 3. In Practical Handbook of Genetic Algorithms: Volume II (pp. 29-42). CRC Press.
